version: '3.9'

networks:
    recursive-network:

services:
    recursive-backend-development:
        build:
            context: ../../
            dockerfile: .docker/development/Dockerfile.dev
        container_name: recursive-backend
        image: recursive-backend:development
        ports:
            - '3000:3000'
        extra_hosts:
            - 'host.docker.internal:host-gateway'
        volumes:
            - ../../:/app
        environment:
            - NODE_ENV=development
        networks:
            - recursive-network
